### ISSUE TITLE
Task appends to existing file instead of rewriting it

### ISSUE THREAD

**Issue by afilina** [mgol/grunt-ng-annotate#40]
The task keeps appending to the end of the target file. It should overwrite the entire file instead.

**Comment by mzgol** [comment]
@afilina Do you have a configuration to share that would show the issue? I just use `grunt.file.write` which overwrites files so I'm not sure how you got that behavior. The task will only concatenate files if you have multiple sources and one destination.

**Comment by eddiemonge** [comment]
@afilina ping

**Comment by afilina** [comment]
I'm not using this project anymore.
