### ISSUE TITLE
how ng-annotate check if it is an angular-based js?

### ISSUE THREAD

**Issue by Awakening-j** [mgol/grunt-ng-annotate#42]
My project is built with angular and jquery files, I want to know how `ng-annotate` check if it need annotate? I wonder if it will annotate on my jquery files.

**Comment by mgol** [comment]
`ng-annotate` transforms all passed files as there's no way to know if it contains Angular code or not. It applies heuristics for checking methods like `factory` or `service` and annotates them.

This whole logic is contained in olov's [ng-annotate](https://github.com/olov/ng-annotate), though, this repo is just a Grunt plugin for it.
