### ISSUE TITLE
ngAnnotate fails on es6 classes that have a constructor but no methods

### ISSUE THREAD

**Issue by mycompassspins** [mgol/grunt-ng-annotate#43]
This produces an Angular unknown provider error when minified:

    export class SomeClass
    {
        /* @ngInject */
        constructor(dep1, dep2)
        {
            this.dep1 = dep1;
            this.dep2 = dep2;

            this.Init = () => console.log('SomeClass.Init');
            this.Init();
        }
    }

This works fine when minified:

    export class SomeClass
    {
        /* @ngInject */
        constructor(dep1, dep2)
        {
            this.dep1 = dep1;
            this.dep2 = dep2;

            this.Init = () => console.log('SomeClass.Init');
            this.Init();
        }

        static FakeMethod()
        {
            return new SomeClass();
        }
    }

**Comment by mgol** [comment]
Please report issues related to output to [ng-annotate](https://github.com/olov/ng-annotate), this is just a Grunt plugin for that.
