### ISSUE TITLE
ngAnnotate:dist - Error when parsing .tmp file

### ISSUE THREAD

**Issue by ChristmasTaco** [mgol/grunt-ng-annotate#45]
Hey all, I'm hoping to get some help with a grunt build that is being aborted by ngAnnotate. Here is what I receive in terminal:

____________________
Running "ngtemplates:dist" (ngtemplates) task
File .tmp/templateCache.js created.
Added .tmp/templateCache.js to 

Running "concat:generated" (concat) task
File .tmp/concat/scripts/vendor.js created.
File .tmp/concat/scripts/scripts.js created.

Running "ngAnnotate:dist" (ngAnnotate) task
Generating ".tmp/concat/scripts/scripts.js" from: ".tmp/concat/scripts/scripts.js"...ERROR
>> error: couldn't process source due to parse error
>> Unexpected token (407:5)
Warning: Task "ngAnnotate:dist" failed. Use --force to continue.

Aborted due to warnings.
_____________________

I'm still fairly green when it comes to this stuff, but I can provide any other details that you need. Please let me know if you think you can help, and thanks in advance!

**Comment by mgol** [comment]
It says the file has a syntax error, that's why it's not working. You didn't post the file so it's hard for me to say more. Could you post contents of `.tmp/concat/scripts/scripts.js` somewhere? You need to do it just after running this erroring command so that we see what file is causing the problem & why.

**Comment by ChristmasTaco** [comment]
@mgol I was able to locate the syntax error, and my confusion was because I actually had a file called scripts.js and was confusing the two. Thanks for the reply, and for continuing to work on this absolutely amazing (read: freaking magical from my perspective) software!

**Comment by mgol** [comment]
Thanks for the kind words but the biggest thanks should go to Olov for making the awesome [ng-annotate](https://github.com/olov/ng-annotate)!

**Comment by science162** [comment]
Hello I have got the same error and here is the code inside script.js.
my error is at the first line and I don't know how to fix it


`
.when('/popular', {
  templateUrl: 'views/popular.html',
  controller: 'PopularCtrl',
  controllerAs: 'popular'
})
'use strict';
/**
 * @ngdoc overview
 * @name cineAngularApp
 * @description
 * # cineAngularApp
 *
 * Main module of the application.
 */
angular
  .module('cineAngularApp', []);

'use strict';

/**
 * @ngdoc function
 * @name cineAngularApp.controller:MainCtrl
 * @description
 * # MainCtrl
 * Controller of the cineAngularApp
 */
angular.module('cineAngularApp')
  .controller('MainCtrl', function () {
    this.awesomeThings = [
      'HTML5 Boilerplate',
      'AngularJS',
      'Karma'
    ];
  });

'use strict';

/**
 * @ngdoc function
 * @name cineAngularApp.controller:PopularCtrl
 * @description
 * # PopularCtrl
 * Controller of the cineAngularApp
 */
angular.module('cineAngularApp')
  .controller('PopularCtrl', function () {
    this.awesomeThings = [
      'HTML5 Boilerplate',
      'AngularJS',
      'Karma'
    ];
  });

angular.module('cineAngularApp').run(['$templateCache', function($templateCache) {
  'use strict';

  $templateCache.put('views/main.html',
    "<div class=\"jumbotron\"> <h1>'Allo, 'Allo!</h1> <p class=\"lead\"> <img src=\"images/yeoman.png\" alt=\"I'm Yeoman\"><br> Always a pleasure scaffolding your apps. </p> <p><a class=\"btn btn-lg btn-success\" ng-href=\"#/\">Splendid!<span class=\"glyphicon glyphicon-ok\"></span></a></p> </div> <div class=\"row marketing\"> <h4>HTML5 Boilerplate</h4> <p> HTML5 Boilerplate is a professional front-end template for building fast, robust, and adaptable web apps or sites. </p> <h4>Angular</h4> <p> AngularJS is a toolset for building the framework most suited to your application development. </p> <h4>Karma</h4> <p>Spectacular Test Runner for JavaScript.</p> </div>"
  );


  $templateCache.put('views/popular.html',
    "<p>This is the popular view.</p>"
  );

}]);

`

**Comment by mgol** [comment]
If you see an issue, please open a new one, this one has long been closed. Please be explicit, though in what's your input, expected output and actual output.

P.S. You need to wrap multiline code in triple backticks, not single ones, otherwise it won't work. You can also specify the language (`js` for JavaScript), like that:
````
```js
JavaScript code
```
````

I fixed the syntax for your current comment.

**Comment by science162** [comment]
Ok, actually it is angular Js. I started buy creating a new root on a views buy runing yo angular:route my_views
And then I run grunt build and it show an error about ngAnnotate saying that I have got and error in the file .temp/concat/scripts/script.js

The code of this file is the one above

**Comment by science162** [comment]
Oh ok sorry here it is 

```js
.when('/popular', {
  templateUrl: 'views/popular.html',
  controller: 'PopularCtrl',
  controllerAs: 'popular'
})
'use strict';
/**
 * @ngdoc overview
 * @name cineAngularApp
 * @description
 * # cineAngularApp
 *
 * Main module of the application.
 */
angular
  .module('cineAngularApp', []);

'use strict';

/**
 * @ngdoc function
 * @name cineAngularApp.controller:MainCtrl
 * @description
 * # MainCtrl
 * Controller of the cineAngularApp
 */
angular.module('cineAngularApp')
  .controller('MainCtrl', function () {
    this.awesomeThings = [
      'HTML5 Boilerplate',
      'AngularJS',
      'Karma'
    ];
  });

'use strict';

/**
 * @ngdoc function
 * @name cineAngularApp.controller:PopularCtrl
 * @description
 * # PopularCtrl
 * Controller of the cineAngularApp
 */
angular.module('cineAngularApp')
  .controller('PopularCtrl', function () {
    this.awesomeThings = [
      'HTML5 Boilerplate',
      'AngularJS',
      'Karma'
    ];
  });

angular.module('cineAngularApp').run(['$templateCache', function($templateCache) {
  'use strict';

  $templateCache.put('views/main.html',
    "<div class=\"jumbotron\"> <h1>'Allo, 'Allo!</h1> <p class=\"lead\"> <img src=\"images/yeoman.png\" alt=\"I'm Yeoman\"><br> Always a pleasure scaffolding your apps. </p> <p><a class=\"btn btn-lg btn-success\" ng-href=\"#/\">Splendid!<span class=\"glyphicon glyphicon-ok\"></span></a></p> </div> <div class=\"row marketing\"> <h4>HTML5 Boilerplate</h4> <p> HTML5 Boilerplate is a professional front-end template for building fast, robust, and adaptable web apps or sites. </p> <h4>Angular</h4> <p> AngularJS is a toolset for building the framework most suited to your application development. </p> <h4>Karma</h4> <p>Spectacular Test Runner for JavaScript.</p> </div>"
  );


  $templateCache.put('views/popular.html',
    "<p>This is the popular view.</p>"
  );

}]);
```
