### ISSUE TITLE
Could we please get a new release for more recent ng-annotate version

### ISSUE THREAD

**Issue by mspe044** [mgol/grunt-ng-annotate#47]
The angular-ui bootstrap team have [moved away from the $modal name space](https://github.com/olov/ng-annotate/issues/200), therefore ng-annotate v1.1.0 or newer is required to automate dependency injection for grunt projects using angular-ui bootstrap.

The may release provided ng-annotate 1.0.1. Would you mind re-releasing with a newer version?

Thanks :)
Mat

**Comment by mgol** [comment]
The latest `grunt-ng-annotate`, `1.0.1` depends on `ng-annotate@^1.0.0` which means it picks up `ng-annotate@1.1.0`. Just reinstall the package and you'll get the new dependency.
