### ISSUE TITLE
angular 1.5 component definition breaks ng-annotate.

### ISSUE THREAD

**Issue by michahell** [mgol/grunt-ng-annotate#49]
for reference only, see: https://github.com/olov/ng-annotate/issues/231?_pjax=%23js-repo-pjax-container

**Comment by mgol** [comment]
Thanks for the report but I can do nothing here. :) It has to be solved by ng-annotate upstream, then the Grunt task will automatically pick up the fixed version.

**Comment by michahell** [comment]
Ah yes, I assumed as much. just for future reference then :)
