### ISSUE TITLE
Need support for Angular 1.5 component's controller

### ISSUE THREAD

**Issue by nabilnaffar** [mgol/grunt-ng-annotate#53]
Current version doesn't support angular 1.5 component's controller annotation.
see commit [5bfb3b1](https://github.com/olov/ng-annotate/commit/5bfb3b124efd29c920fe13e871e92549260d2f62) in ng-annotate.

**Comment by mgol** [comment]
This task doesn't influence the input types in any way; everything that works in `ng-annotate` should work here as well. Are you using the latest version? What's your code?
