### ISSUE TITLE
Conditional Files

### ISSUE THREAD

**Issue by molerat619** [mgol/grunt-ng-annotate#54]
Hi!

I have a css file that get's loaded only if the user has picked a language that is written from right-to-left. It looks like that:

`<link rel="stylesheet" href="assets/css/bootstrap-rtl.min.css" ng-if="lang.dir == 'rtl'" />`

But ng-annotate takes it when building the app and puts it into app.css of course. Then all languages get written right-to-left, which is wrong. What's the best way to avoid that?

**Comment by mgol** [comment]
ng-annotate only transforms JavaScript files that you feed to it. I'm not sure how it might influence any CSS files on your page. Could you elaborate?

**Comment by mgol** [comment]
I'll close it for now but if you provide more information I can reopen.
