### ISSUE TITLE
separator option ignored?

### ISSUE THREAD

**Issue by molerat619** [mgol/grunt-ng-annotate#55]
Hey there!

I have this Grunt task:

`ngAnnotate: {
      options: {
        separator: ';',
        singleQuotes: true
      },
      dist: {
        files: [{
          expand: true,
          cwd: '.tmp/concat',
          src: '**/*.js',
          dest: '.tmp/concat'
        }]
      }
    },`

But for some reason, I end up having a problem in the resulting vendor.js file. I get that line:

`angular.module("ui.bootstrap.carousel").run(function(){!angular.$$csp()&&angular.element(document).find("head").prepend('<style type="text/css">.ng-animate.item:not(.left):not(.right){-webkit-transition:0s ease-in-out left;transition:0s ease-in-out left}</style>')})(function(a,b){"object"==typeof`

Look close to the end before the last `function` --> there is no comma separator. That causes my angular module not to run anymore.

**Comment by mgol** [comment]
Thanks for the report. I have a [test ensuring the `separator` option works](https://github.com/mgol/grunt-ng-annotate/blob/master/test/fixtures/concatenated-separator.js) so it looks weird. If it doesn't work in a specific case for some reason, I'd need a concrete test case that I could look at. You could e.g. submit a PR with a new test case (you should add config after [these lines in `Gruntfile.js`](https://github.com/mgol/grunt-ng-annotate/blob/902575f/Gruntfile.js#L167-L178), create source & expected final files in `test/fixtures` and add a test similar to what's in [test/spec/api.js#L51-L53](https://github.com/mgol/grunt-ng-annotate/blob/902575f/test/spec/api.js#L51-L53) that fails.

Would you be willing to try? Let me know if you have any problems with that.

**Comment by mgol** [comment]
I'll close it for now but if you provide more information I can reopen.
