### ISSUE TITLE
Getting Strict mode error on latest version

### ISSUE THREAD

**Issue by farhansalam** [mgol/grunt-ng-annotate#56]
Getting this error with

Node version `5.0.0`
grunt-ng-annotate version `latest`
`[INFO] Running 'grunt local' in /Users/farhan/Documents/projects/bizi/bizi-admin
[ERROR]
[ERROR] /Users/farhan/Documents/projects/bizi/bizi-admin/node_modules/grunt-ng-annotate/tasks/ng-annotate.js:11
[ERROR] const path = require('path');
[ERROR] ^^^^^
[INFO] Loading "ng-annotate.js" tasks...ERROR
[INFO] >> SyntaxError: Use of const in strict mode.
[INFO] Warning: Task "ngAnnotate:main" not found. Use --force to continue.
[INFO]
[INFO] Aborted due to warnings.`

**Comment by mgol** [comment]
Are you sure it's Node 5.0? It supports `const` in strict mode.

Also, note that Node 5 is not supported, the only versions supported currently are 4, 6 & 7 (see [the proper `README` section](https://github.com/mgol/grunt-ng-annotate#supported-nodejs-versions).

It seems to me you're running it in Node 0.10 or 0.12.

**Comment by mgol** [comment]
I'll close it for now but if you provide more information I can reopen.

**Comment by NitinStar** [comment]
I am also facing same issue with grunt-ng-annonate v 3.0.0 and Node 0.12.7.  is it not supporting Node 0.12.7? Please reply.

**Comment by mgol** [comment]
@NitinStar Yes, Node.js older than 4 is no longer supported.
