### ISSUE TITLE
ngAnnotate:dist - Error of parsing during build 

### ISSUE THREAD

**Issue by charmipatel06** [mgol/grunt-ng-annotate#60]
I'm hoping to get some help with a grunt build that is being aborted by ngAnnotate. Here is what I receive in terminal:

![Screenshot (29)](https://user-images.githubusercontent.com/22962091/71512929-42edcf00-28be-11ea-8a25-bccf92163670.png)

I'm still fairly green when it comes to this type of stuff, but I can provide any other details that you need. Also I am attaching screenshot of script file of a specified line. Please let me know if you think you can help, and thanks in advance!

Script.js

![Screenshot (30)](https://user-images.githubusercontent.com/22962091/71513109-0f5f7480-28bf-11ea-82d2-b14e16cc375f.png)

**Comment by mgol** [comment]
Which Node.js version do you use? Invoke `node --version` to check.

**Comment by charmipatel06** [comment]
I am using v10.16.0 of Node.js..

**Comment by mgol** [comment]
Which version of `grunt-ng-annotate`? Also, it'd help if you could prepare a repository that reproduces the issue.

**Comment by charmipatel06** [comment]
3.0.0 version of grunt-ng-annotate.

**Comment by charmipatel06** [comment]
I have updated the Node.js version and it is working now successfully.
