### ISSUE TITLE
remove duplicate 'use strict' statements when concatenating?

### ISSUE THREAD

**Issue by aderowbotham** [mgol/grunt-ng-annotate#9]
When using `grunt-ng-annotate` like this:

```
ngAnnotate: {
  app: {
    files: {
      "concat.js": ["a.js", "b.js", "c.js"]
    },
  },  
}
```

...if you have "use strict'' statements in those source files the concatenated file then contains multiple repetitions of the statement.

An option  to prevent this would be great for cleanup purposes.

**Comment by ben-crowhurst** [comment]
+1
